# Generated by Django 5.1.3 on 2025-04-27 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_accepted_by_buyer', models.BooleanField(default=False, verbose_name='Подтверждено покупателем')),
                ('is_accepted_by_author', models.BooleanField(default=False, verbose_name='Подтверждено автором')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'created_at'], name='store_playl_user_id_41c4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'purchase_date'], name='store_purch_user_id_b9a61f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer', 'created_at'], name='store_trans_buyer_i_1666ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='purchase_total_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='song_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_amount_non_negative'),
        ),
        migrations.AddField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='store.purchase', verbose_name='Покупка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='store.song', verbose_name='Песня'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['purchase', 'buyer', 'author'], name='store_contr_purchas_f58a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='store_contr_created_ba4a5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('purchase', 'buyer', 'author', 'song'), name='unique_contract'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='contract_amount_non_negative'),
        ),
    ]
